### ISSUE TITLE
Rename and move to cf-community

### ISSUE THREAD

**Issue by drnic** [cloudfoundry-community/go-cfenv#3]
[cc @jambay for his visibility and thoughts]

@joefitzgerald I thinking about how we could rename this project (golang client library for access to ENV vars within a CF app) and bring it together with other CF ENV client libraries. @pmuellr has been working on a node.js one. There is a ruby one somewhere with a different name & location too. Probably a Java one too in the https://github.com/cloudfoundry-community/cf-java-component repo somewhere. (I DID SO MUCH RESEARCH FOR THIS EMAIL).

I was thinking that perhaps we rename the repos to have a similar name suffix (`<lang>-cf-env`) or prefix (`cf-env-<lang>`) and move them all into cf-community or cf-incubator.

@pmuellr noted that https://github.com/cloudfoundry-community/cf-env perhaps had a name that also claimed to be a client library. Or at least would get in the way of the naming scheme above. Perhaps it can be renamed to `show-env`.

**Comment by markpollack** [comment]
I know this is an old thread and I just happened upon it by chance since I am writing such a library now.

Java actually does have a need for this type of library based on experience over the years.  There are many reasons.  The 'connector' libraries https://cloud.spring.io/spring-cloud-connectors/ has been to library to use for parsing VCAP_SERVICES and creating various Java objects, (DataSource and such). 
 However, it has several drawbacks.  First, they are rather limited in what can be configured, for example requiring coding changes to set connection pool properties.  Second, with Spring Boot now providing the best experience for creating these infrastructure objects, we should simply delegate to Boot 99% of the time.   There is also tons of incidental complexity with the design of the connector library and the default 'auto-reconfiguration' of the java build pack swapping out bean definitions.  Taken together it is hard to figure out what is going on, has been brittle, and it is not easy to add new functionality in my experience.

All that said, I started to develop a new library whose goal is to provide a lightweight library in the style of <platform>-cfenv projects and pass along the credential information to Spring Boot properties so it's autoconfiguration can create the infrastructure objects (DataSource).

It is **very** early days, but getting some feedback would be appreciated.

https://github.com/spring-projects-experimental/spring-cfenv
